read -p "请输入要查看的org: (1=org1,2=org2,3=org3,4=org4):" num
echo "org${num}的keyid:"
version="V1.0.0"
#version="v2.1.0_alpha"
certs_path="../chainmaker-go/build/release/chainmaker-${version}-wx-org${num}.chainmaker.org/config/wx-org${num}.chainmaker.org/certs"
echo "--------------------------keys------------------------"
echo "${certs_path}/node/common1/common1.sign.key"
cat "${certs_path}/node/common1/common1.sign.key"
echo ""
echo "${certs_path}/node/consensus1/consensus1.sign.key"
cat "${certs_path}/node/consensus1/consensus1.sign.key"
echo ""
echo "${certs_path}/user/admin1/admin1.sign.key"
cat "${certs_path}/user/admin1/admin1.sign.key"
echo ""
echo "${certs_path}/user/client1/client1.sign.key"
cat "${certs_path}/user/client1/client1.sign.key"
echo ""
echo "---------------------------nodeid------------------------"
echo "${certs_path}/node/consensus1/consensus1.nodeid"
cat "${certs_path}/node/consensus1/consensus1.nodeid"
echo ""
