./cmc query block-by-height 0 --chain-id=chain1 --sdk-conf-path=./testdata/sdk_config.yml >>/home/fxy/debug_tmp/2xpk_block0.json
./cmc query block-by-height 1 --chain-id=chain1 --sdk-conf-path=./testdata/sdk_config.yml >>/home/fxy/debug_tmp/2xpk_block1.json
./cmc query block-by-height 2 --chain-id=chain1 --sdk-conf-path=./testdata/sdk_config.yml >>/home/fxy/debug_tmp/2xpk_block2.json
./cmc query block-by-height 30 --chain-id=chain1 --sdk-conf-path=./testdata/sdk_config.yml >>/home/fxy/debug_tmp/2xpk_block30.json
./cmc query block-by-height 40 --chain-id=chain1 --sdk-conf-path=./testdata/sdk_config.yml >>/home/fxy/debug_tmp/2xpk_block40.json
./cmc query block-by-height 50 --chain-id=chain1 --sdk-conf-path=./testdata/sdk_config.yml >>/home/fxy/debug_tmp/2xpk_block50.json
./cmc query block-by-height 60 --chain-id=chain1 --sdk-conf-path=./testdata/sdk_config.yml >>/home/fxy/debug_tmp/2xpk_block60.json
./cmc query block-by-height 67 --chain-id=chain1 --sdk-conf-path=./testdata/sdk_config.yml >>/home/fxy/debug_tmp/2xpk_block67.json
./cmc query block-by-height 70 --chain-id=chain1 --sdk-conf-path=./testdata/sdk_config.yml >>/home/fxy/debug_tmp/2xpk_block70.json
